import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import QueryProvider from '@/providers/query/QueryProvider';
import { ContextProvider } from '@/providers/context/ContextProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <ContextProvider>
            {children}
            <ToastContainer />  
          </ContextProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
